PN-243 client del servizio mock di address-book
pagopa/pn-commons pull request #1
Opened 2021-08-20 11:27 UTC by marco-vit-pagopa

Semplice client del mock che verrà utilizzato per il PoC

2021-08-20 13:18 UTC, russo-f requested changes
Grazie, fatta anche questa. C'è almeno 1 commento da approfondire.

2021-08-20 13:18 UTC, russo-f commented on src/main/java/it/pagopa/pn/commons/pnclients/addressbook/AddressBook.java
> +    AddressBookEntry getAddresses( String taxId );
**?**
``taxId`` è un nome così o è li per dire _codice fiscale_?

Se è la seconda, mi raccomando a chiarire anche nel codice che non è il codice vero, ma il suo token.

Chiamalo ``tokenisedFiscalCode`` ad es. o in generale ``tokenisedXxx``.

Da applicarsi a cascata altrove se necessario.

2021-08-20 13:18 UTC, russo-f commented on src/main/java/it/pagopa/pn/commons/pnclients/addressbook/AddressBookImpl.java
> +            throw new IllegalStateException("Error calling url " + addressBookGetUrl + " status "+ response.getStatusCodeValue() );
**Importante**
Consiglio un'altra eccezione, magari puoi semplicemente propagare quella che hai già?
Non c'e' un ``IllegalState`` se si ha un ``4XX`` o un ``5XX``, sono stati legali per il sistema.

2021-08-20 13:18 UTC, russo-f commented on src/main/java/it/pagopa/pn/commons/pnclients/addressbook/AddressBookImpl.java
> +        return responseBody;
**?**
Si deve per forza produrre un risultato se risultato non c'e'?

Se e' inevitabile, consiglio di creare un campo ``static final`` con la ``EMPTY_RSP`` pre-canned.

2021-08-20 13:18 UTC, russo-f commented on src/test/java/it/pagopa/pn/commons/pnclients/addressbook/AddressBookTestIT.java
> +public class AddressBookTestIT {
**?**
Come mai ``IT`` in fondo? Pura curiosità :)

2021-08-20 15:43 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/commons/pnclients/addressbook/AddressBookImpl.java
> +        return responseBody;
Utilizzato optional :)

2021-08-23 09:11 UTC, russo-f commented on src/main/java/it/pagopa/pn/commons/abstractions/impl/MiddlewareTypes.java
>  public class MiddlewareTypes {
**?**
Come mai non una ``enum``?

2021-08-23 09:16 UTC, russo-f approved these changes
OK, ship it. Buone le prime eccezioni applicative aggiunte.
Off-line ti do altri consigli su come farle crescere un po' se vuoi.

Ti ho lasciato solo un commento se non erro sull'uso di una classe dove andrebbe meglio una enum.

E' minor, quindi approval dato, ma rivedilo e se e' il caso fissa.

Grazie.

2021-08-23 09:17 UTC, russo-f commented
PS: nel complesso era ancora un po' troppo lunga come review, cerca di ridurre le prossime, e' facile perdere il fuoco dopo un po' almeno per me.

2021-08-23 10:16 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/commons/abstractions/impl/MiddlewareTypes.java
>  public class MiddlewareTypes {
Perché la uso nell'annotazione @ConditionalOnProperty che richiede una stringa. e nelle annotazioni java non posso utilizzare Enum::CONSTANT.name() perché viene vista come invocazione di metodo potenzialmente non costante

2021-08-23 10:17 UTC, merged